# -*- coding: utf-8 -*-
"""20230913_4120E007

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MjisHyBlu-IiLZatnCl8SMSgXklmWNwb
"""

3**211